"""BPI tint colour reference — a shipped name → hex table and its picker popup.

BPI (Brain Power Inc.) are the dominant supplier of optical lens dyes, so when
a maker reaches for a lens colour they usually already have a BPI tint name in
mind. This module ships an approximate on-screen hex for each tint in their
published catalog and offers it as a swatch grid, so picking "B&L G-15" is one
click instead of a guess in the colour wheel.

Only the numbers ship: ``resources/bpi_tints.json`` holds names and hex values,
which the popup paints as its own chips. No BPI artwork is bundled or drawn.
The table is regenerated by ``scripts/scrape_bpi_tints.py``.

The values are approximate and unofficial — sampled from BPI's own display
swatches, which are not colorimetric and do not track how deep a given lens
will actually come out. GuildDraw is not affiliated with BPI; the tint names
are theirs.
"""
from __future__ import annotations

import json
from pathlib import Path

from PySide6.QtCore import Qt, QSize, Signal
from PySide6.QtGui import QColor, QIcon, QPainter, QPen, QPixmap
from PySide6.QtWidgets import (
    QGridLayout, QLabel, QLineEdit, QScrollArea, QToolButton, QVBoxLayout,
    QWidget,
)

_DATA_FILE = Path(__file__).parent / "resources" / "bpi_tints.json"

_COLUMNS   = 7
_CHIP_PX   = 24

_cache: list[dict] | None = None


def load_tints() -> list[dict]:
    """Shipped tint table: ``[{"name", "family", "hex", "note"}, …]``.

    Returns [] if the file is missing or unreadable — the picker button hides
    itself in that case rather than the app failing to start.
    """
    global _cache
    if _cache is None:
        try:
            data = json.loads(_DATA_FILE.read_text(encoding="utf-8"))
            _cache = [t for t in data.get("tints", [])
                      if isinstance(t.get("hex"), str)
                      and QColor(t["hex"]).isValid()]
        except (OSError, ValueError):
            _cache = []
    return _cache


def _chip(color_hex: str) -> QIcon:
    """A flat swatch of *color_hex* with a hairline border, so a near-white
    tint still reads as a chip against the popup background."""
    pm = QPixmap(_CHIP_PX, _CHIP_PX)
    pm.fill(QColor(color_hex))
    p = QPainter(pm)
    p.setPen(QPen(QColor(0, 0, 0, 60)))
    p.drawRect(0, 0, _CHIP_PX - 1, _CHIP_PX - 1)
    p.end()
    return QIcon(pm)


class TintPicker(QWidget):
    """Popup grid of BPI tint swatches. Emits the chosen hex, then closes.

    Shown with ``popup.show_under(button)``; being a Qt popup it closes on any
    click outside itself or on Esc.
    """

    tint_picked = Signal(str)      # "#rrggbb"

    def __init__(self, parent=None, title: str = "BPI tint reference"):
        super().__init__(parent, Qt.WindowType.Popup)
        # A popup is built per open and parented to the main window, so without
        # this each visit to the reference would strand the whole grid — 164
        # buttons and their pixmaps — alive for the rest of the session.
        self.setAttribute(Qt.WidgetAttribute.WA_DeleteOnClose)
        self._buttons: list[tuple[QToolButton, str]] = []

        lay = QVBoxLayout(self)
        lay.setContentsMargins(8, 8, 8, 8)
        lay.setSpacing(6)

        heading = QLabel(title)
        heading.setStyleSheet("font-weight: 600;")
        lay.addWidget(heading)

        self._search = QLineEdit()
        self._search.setPlaceholderText("Filter by name…")
        self._search.setClearButtonEnabled(True)
        self._search.textChanged.connect(self._apply_filter)
        lay.addWidget(self._search)

        # Grid inside a top-packed column: the scroll area stretches its widget
        # to the viewport, and without the trailing stretch a short filter
        # result spreads its two rows down the whole popup.
        grid_host = QWidget()
        host_lay  = QVBoxLayout(grid_host)
        host_lay.setContentsMargins(0, 0, 0, 0)
        host_lay.setSpacing(0)
        grid_inner = QWidget()
        host_lay.addWidget(grid_inner)
        host_lay.addStretch()
        self._grid = QGridLayout(grid_inner)
        self._grid.setContentsMargins(0, 0, 0, 0)
        self._grid.setSpacing(3)
        for i, tint in enumerate(load_tints()):
            btn = QToolButton()
            btn.setIcon(_chip(tint["hex"]))
            btn.setIconSize(QSize(_CHIP_PX, _CHIP_PX))
            btn.setAutoRaise(True)
            note = f"\n{tint['note']}" if tint.get("note") else ""
            btn.setToolTip(f"{tint['name']}\n{tint['hex']}  ·  "
                           f"{tint.get('family', '')} tint{note}")
            btn.clicked.connect(
                lambda _checked=False, h=tint["hex"]: self._pick(h))
            self._grid.addWidget(btn, i // _COLUMNS, i % _COLUMNS)
            self._buttons.append((btn, f"{tint['name']} {tint.get('family', '')}".lower()))

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(scroll.Shape.NoFrame)
        scroll.setWidget(grid_host)
        scroll.setMinimumHeight(240)
        lay.addWidget(scroll)

        self._count = QLabel()
        self._count.setStyleSheet("color: palette(mid); font-size: 10px;")
        lay.addWidget(self._count)

        footer = QLabel(
            "Approximate screen colours from BPI's published swatches — "
            "unofficial, not a dye-lot match. Names are BPI's.")
        footer.setWordWrap(True)
        footer.setStyleSheet("color: palette(mid); font-size: 10px;")
        lay.addWidget(footer)

        self.setMinimumWidth(_COLUMNS * (_CHIP_PX + 12) + 40)
        self._apply_filter("")

    def _pick(self, color_hex: str):
        self.tint_picked.emit(color_hex)
        self.close()

    def _apply_filter(self, text: str):
        """Re-flow the grid to the matching chips.

        Hiding in place would leave the filtered-out cells as holes, so the
        survivors are re-packed from the top left — a search for "gray" reads
        as a short block of greys, not a scatter across seven rows.
        """
        needle  = text.strip().lower()
        shown   = 0
        for btn, haystack in self._buttons:
            if needle and needle not in haystack:
                btn.setVisible(False)
                continue
            self._grid.removeWidget(btn)
            self._grid.addWidget(btn, shown // _COLUMNS, shown % _COLUMNS)
            btn.setVisible(True)
            shown += 1
        total = len(self._buttons)
        if needle:
            self._count.setText(f"{shown} of {total} tints"
                                if shown else f"No tint matches “{text.strip()}”")
        else:
            self._count.setText(f"{total} tints")

    def show_under(self, widget: QWidget):
        """Drop the popup below *widget*, nudged to stay on screen."""
        pos = widget.mapToGlobal(widget.rect().bottomLeft())
        self.adjustSize()
        screen = widget.screen()
        if screen is not None:
            avail = screen.availableGeometry()
            x = min(pos.x(), avail.right() - self.width() - 4)
            y = pos.y()
            if y + self.height() > avail.bottom():
                y = max(avail.top(), pos.y() - self.height() - widget.height())
            pos.setX(max(avail.left() + 4, x))
            pos.setY(y)
        self.move(pos)
        self.show()
        self._search.setFocus()
